import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

import { Toaster as SonnerToaster } from "sonner"
import { Toaster } from "~/components/ui/toaster";
import Navbar from "~/components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="max-w-[1244px] mx-auto px-[36px] my-[36px]">
          <div className="my-[36px]">
            <Navbar />
          </div>
          {children}
          <SonnerToaster />
          <Toaster />
        </div>
      </body>
    </html>
  );
}
